services:
  - type: web
    name: capstone-backend
    env: python
    region: singapore
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
