# Generated by Django 6.1.1 on 2026-10-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='ai_insights',
            field=models.JSONField(blank=True, default=dict, help_text='Grounded AI Recruiter Insights JSON'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='preferred_skill_match_score',
            field=models.FloatField(default=0.0, help_text='Preferred/Nice-to-have skills fit'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='project_match_score',
            field=models.FloatField(default=0.0, help_text='Projects and achievement relevance'),
        ),
        migrations.AddField(
            model_name='resume',
            name='redacted_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='redacted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='education_match_score',
            field=models.FloatField(default=0.0, help_text='Education level and credentials fit'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='experience_match_score',
            field=models.FloatField(default=0.0, help_text='Relevant work experience fit'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='semantic_match_score',
            field=models.FloatField(default=0.0, help_text='Contextual duties & responsibilities fit'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='skill_match_score',
            field=models.FloatField(default=0.0, help_text='Required/Must-have skills fit'),
        ),
    ]
